### ISSUE TITLE
Image in post content with css class (fig-100) are not centered

### ISSUE THREAD

**Issue by kaedea** [LouisBarranqueiro/tranquilpeak-hexo-theme#107]
In my case, I wanna set the content's `max-width` larger than 750px. Everything just works well except the `Fancybox`.
![enter image description here](https://lh3.googleusercontent.com/-NbTWK7d45HI/Vgy3YWgdktI/AAAAAAAACBI/oR0cFPv6EdQ/s800/BaiduShurufa_2015-10-1_12-19-47.jpg "BaiduShurufa_2015-10-1_12-19-47.jpg")

When the `max-width <= 750px`, it looks well.
![enter image description here](https://lh3.googleusercontent.com/-M3Gg4ID-VEU/Vgy5EgY1sGI/AAAAAAAACBg/_QKinvHaoQk/s800/BaiduShurufa_2015-10-1_12-20-3.jpg "BaiduShurufa_2015-10-1_12-20-3.jpg")

BTW, do you forget to set the `margin` for the `fig-100`. 
![enter image description here](https://lh3.googleusercontent.com/-_cZ_A0GdYEM/Vgy5b3M4DQI/AAAAAAAACB8/AdA-Ff2eysU/s800/QQ%25E6%2588%25AA%25E5%259B%25BE20151001122146.jpg "QQ截图20151001122146.jpg")

I try to fix this but not even find out the reasion for this problem. Pls give some hints to hlep.

**Comment by LouisBarranqueiro** [comment]
There is no bugs, thumbnail are just perfectly sized to fit with the `max-with` set to `750px`. just remove the second url in the tag because the thumbnail is not enough larger. :
Eg : `{% image fancybox fig-25 http://res.cloudinary.com/tranquilpeak-hexo-theme/image/upload/v1438892905/car-22.jpg http://res.cloudinary.com/tranquilpeak-hexo-theme/image/upload/w_185/v1438892905/car-22.jpg %}`
to : ` {% image fancybox fig-25 http://res.cloudinary.com/tranquilpeak-hexo-theme/image/upload/v1438892905/car-22.jpg %}`

**Comment by kaedea** [comment]
@LouisBarranqueiro 
I am tring to use some larger images instead.er images instead.
BTW, do you forget to set the margin for the fig-100.
The first image's left align seem not to be good.

**Comment by LouisBarranqueiro** [comment]
you are right! Thanks you for this detail. I will fix this:  `margin: 2px;` missed for `fig-100` css class.
