### ISSUE TITLE
Better if replace sass with stylus.

### ISSUE THREAD

**Issue by h404bi** [LouisBarranqueiro/tranquilpeak-hexo-theme#12]
What a good theme!

I run hexo in Windows with just nodejs environment, without ruby, therefore I cannot build this theme.
I think it will be more usable by using nodejs based css preprocessor like hexo's official theme. :-]

![20150517210216](https://cloud.githubusercontent.com/assets/5764917/7670521/75f51b7a-fcda-11e4-956b-4f81b309d1d7.jpg)

**Comment by LouisBarranqueiro** [comment]
Thank you man!   
@haichao592 find the solution to this problem. I'm surprised that you need ruby and gem sass to run this command. I didn't notice that because i got them by default before I written this theme. I have asked him to create an issue to help other people. In waiting, follow this : 
1. Install [ruby](https://www.ruby-lang.org/en/)
2. Install [rubyGem](https://rubygems.org/pages/download) (packages manager for ruby like npm for node.js)
3. Run `gem install sass`  
and it should work. :)

**Comment by LouisBarranqueiro** [comment]
The version [1.0.2](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.0.2) resolve this issue. Thank you for the idea :)
