### ISSUE TITLE
Hexo s failed

### ISSUE THREAD

**Issue by cnio** [LouisBarranqueiro/tranquilpeak-hexo-theme#124]
while executing `hexo s` after `hexo g`,there is a `FATAL Something's  wrong.`
generating the public/ work well,but the last step `hexo s` can't work.
so I changed the theme to landscape, the `hexo s` still not work. But at the first time I visited `0.0.0.0:4000` in browser using the landscape theme , all was OK.Now I have no idea where it goes wrong.

**Comment by LouisBarranqueiro** [comment]
I bet you are using IntelliJ IDE or a virtual terminal through an IDE, am I right?

**Comment by cnio** [comment]
I am always using sublime.

**Comment by LouisBarranqueiro** [comment]
what's your OS?

**Comment by cnio** [comment]
Linuxmint17

**Comment by LouisBarranqueiro** [comment]
and do you use the terminal integrated in sublime or the native terminal?

**Comment by cnio** [comment]
the native terminal

**Comment by LouisBarranqueiro** [comment]
I had this error when i'm using the virtual terminal of IntelliJ IDEA. I'm on OS X 10.11. When I'm using the native terminal, it works. Try to delete the `node_modules` directory in `tranquilpeak` theme directory. It should work.

I think this error is generated because Hexo analyse all files and some exceptions are not handled. You can see it when you enter `hexo generate --debug`, It analyse `node_modules` directory. I had this error 3 month ago. Currently, it works... it's very strange.

**Comment by cnio** [comment]
thanks a lot ,I will  try to solve it. if I fixed,I will feedback to you.

**Comment by LouisBarranqueiro** [comment]
Author of Hexo will implement a feature to ignore node_modules folder. I'm waiting it because I think it will solve this issue :)

**Comment by cnio** [comment]
Yeah!!! but when I only delete the `node_modules` directory in `tranquilpeak` , it still not work. so I try to delete `node_modules` in `Blog`(hexo init) directory,and `npm install ` again, it works,so amazing, so puzzle!  whatever, so thanks.

**Comment by LouisBarranqueiro** [comment]
your welcome :D
