### ISSUE TITLE
How to config "continue reading" page structure?

### ISSUE THREAD

**Issue by cleechtech** [LouisBarranqueiro/tranquilpeak-hexo-theme#128]
Over at the [demo](http://louisbarranqueiro.github.io/tranquilpeak-hexo-theme/) page the blog has a large post and then smaller posts that are truncated with the "Continue reading" button.

![screen shot 2015-10-23 at 4 44 57 pm](https://cloud.githubusercontent.com/assets/3578908/10708152/565f4a14-79b3-11e5-9592-e1af38c71040.png)

My deployment has the full text of every blog post and a small side bar:

![screen shot 2015-10-23 at 6 25 05 pm](https://cloud.githubusercontent.com/assets/3578908/10708157/82fcb3cc-79b3-11e5-9998-f04c81138675.png)

I would like to have my website look more like the demo with a large sidebar and the "continue reading" button. My _config.yaml customization section is the same as the one in this repo. What can I change so that the site has this different layout? Thank you for this awesome project

**Comment by cleechtech** [comment]
For the larger sidebar add `sidebar_behavior: 1`. Still not sure about how to implement the "continue reading" layout though

**Comment by h404bi** [comment]
**Again, please take a careful look at documents.**
Other people cannot help you all the time. That's why there are docs there. :-|

Use `<!-- more -->` tag to define a post excerpt. Content after `<!-- more -->` tag would not display. For more, [doc](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/user.md#define-post-excerpt) and [demo source](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/tree/source-blog-posts).

**Comment by cleechtech** [comment]
Okay thank you. The link to the demo source code and docs was very helpful. Great project!
