### ISSUE TITLE
mathjax support?

### ISSUE THREAD

**Issue by luoyetx** [LouisBarranqueiro/tranquilpeak-hexo-theme#148]
great theme! Recently I try this theme but find the latex formulas are not able to display. Does the theme currently support mathjax? if not, any plan for supporting it? thx :-)

**Comment by h404bi** [comment]
You may use mathjax hexo plugins (e.g. [hexo-math](https://github.com/akfish/hexo-math)) if you want this feature, instead of asking about feature integration. Using plugins can be low coupling, means you can switch between themes, and can still use mathjax even those themes without mathjax support.

**Comment by luoyetx** [comment]
many thanks. I will try to use some plugins to see if it works. :smile:

**Comment by luoyetx** [comment]
really works! thx again!
