### ISSUE TITLE
When running localhost hexo server thumbnailImage is loading from global.url

### ISSUE THREAD

**Issue by k155la3** [LouisBarranqueiro/tranquilpeak-hexo-theme#177]

**Comment by LouisBarranqueiro** [comment]
you means config.url? that is normal behavior

**Comment by k155la3** [comment]
yes, `config.url`, so thumbnail can't be previewed on localhost?

**Comment by LouisBarranqueiro** [comment]
When you are writing posts, change url to localhost and before deploy, set the remote url. This is what i'm doing when i'm working on the theme or writing posts

**Comment by k155la3** [comment]
Gotcha. Thanks!

**Comment by LouisBarranqueiro** [comment]
your welcome :)

**Comment by acyuta108** [comment]
How about adding this (workaround) to the docs. I spent a few hours debugging my paths, etc :(. 

Perhaps fixing it instead of this workaround. It adds one more thing to remember before deploying, and I manage a very large blog, so it takes long to generate and deploy before I realize I forgot to update the config.url.
I am not very expert in Hexo, but maybe detecting if it's running hexo server opposed to hexo generate to figure out the thumbnail path? Or why not just using the img_url helper to create the path for the thumbnail, like any other image in the post?
Thanks for all the good work.

**Comment by LouisBarranqueiro** [comment]
Hey @acyuta108, this feature should be implemented at Hexo level, so ask it on Hexo repository

**Comment by acyuta108** [comment]
Ok, thanks!
