### ISSUE TITLE
missing .gitignore?

### ISSUE THREAD

**Issue by tjwudi** [LouisBarranqueiro/tranquilpeak-hexo-theme#22]
May be good to add **.gitignore** to the project

**Comment by LouisBarranqueiro** [comment]
I didn't add a .gitignore file to the project because everyone have different files and folder to ignore depend on their IDE and operating system. And if they edit the .gitignore, they will have a file to commit. But adding a general `.gitignore` content in the documentation to help developers would be a good idea. I'm on.

**Comment by tjwudi** [comment]
Well, I would suggest using `git submodule` workflow for using this project. If developers use `git submodule` then you can add **.gitignore** without messing up the whole blog.

**Comment by LouisBarranqueiro** [comment]
You are right, i will add a .gitignore file in next version

**Comment by LouisBarranqueiro** [comment]
I have added a gitignore file on the `dev`branch. Soon in the next release :)

**Comment by tjwudi** [comment]
Awesome!

**Comment by LouisBarranqueiro** [comment]
Thank you for your contribution :)
