### ISSUE TITLE
how to add a page?

### ISSUE THREAD

**Issue by digifu** [LouisBarranqueiro/tranquilpeak-hexo-theme#35]
I tried to add a page but pictures and links are not working. Is it possible to add pages with your theme?

**Comment by LouisBarranqueiro** [comment]
Of course it's possible. Can you show me the source code of your page and folder architecture: `public/YOUR_PAGE` and `source/YOUR_PAGE`? Check that your images must be in `public/YOUR_PAGE/` folder to be available from `index.html` page with relative url like `photo.png`. if there is a subfolder like `public/YOUR_PAGE/subfolder/`, images will be reach with `subfolder/photo.png` from `public/YOUR_PAGE/index.html`

**Comment by digifu** [comment]
When I click the "Test" link, I can see the page but the pictures are not working, instead of the last entry. 

![screenshot - 27 06 2015 - 15 52 08](https://cloud.githubusercontent.com/assets/8808779/8391063/ae3362d8-1ce4-11e5-8748-621f5dec3254.png)

![screenshot - 27 06 2015 - 15 52 42](https://cloud.githubusercontent.com/assets/8808779/8391145/6b8b72c8-1ce8-11e5-8878-51f6630b813f.png)

The picture are in the subfolder index, like ``/source/test/index/laos.jpg``
Here is the code of the ``/source/test/index.md``

``title: "test"``
``thumbnailImage: index/laos.jpg``
``coverImage: index/laos1.jpg``
``photos:``
``    - index/myanmar.jpg``
``    - index/laos.jpg``
``    - index/laos1.jpg``
``---``
``{% asset_img index/laos.jpg [title] %}``
``![Alt text](/test/index/laos.jpg)``

**Comment by LouisBarranqueiro** [comment]
you're right, there is a bug with image urls. I would like to have your opinion. I take an example:  
you create a page "test". so in this folder, you have `index` folder and a file `index.md` file.
in `test` folder, you create an other file `hello.md` and a folder `hello`. 
So this 2 posts in `test `page will be reachable at `http://yourblog.com/test/index.html` and `http://yourblog.com/test/hello.html`.  Each page(`hello.md` and `index.md` have images) I would like to know what do you prefer in front matter.
**1** `hello.md` content :  
``` mardown
title: "hello"
thumbnailImage: hello/tranquilpeak.png
coverImage: hello/tranquilpeak.png
photos:
- hello/tranquilpeak.png
---

![Alt text](hello/tranquilpeak.png)
```

**2** `hello.md` content :  
``` mardown
title: "hello"
thumbnailImage: tranquilpeak.png
coverImage: tranquilpeak.png
photos:
- tranquilpeak.png
---

![Alt text](hello. tranquilpeak.png)
```

Normally, tranquilpeak have the second behavior for posts because it easier for user to just write the relative url. But a page can have multiple posts in, so you want to maybe share images between them, or other things like that. Do you want that front matter reach `/your_page/` folder or `/your_page/your_post_folder/`, in your case `/test/` or `/test/hello/` ? Tell me :) behavior **1** or **2**?

**Comment by digifu** [comment]
Sorry for the delay. Went from Asia back to Europe.

I would prefer 1. But only because I don't see the advantage of 2. What is the point in having posts for a single page? Or do you mean subpages?

**Comment by LouisBarranqueiro** [comment]
Currently, for posts, the behavior is **2**. User doesn't need to write the folder name everywhere, and if he change the title of the post (then the name of the folder which contains photos) , he will not have to rename each lines where there is the old folder name

**Comment by LouisBarranqueiro** [comment]
i'm still waiting your answer to push changes :)

**Comment by digifu** [comment]
I think 2. is better. Tranquilpeak and hexo is mainly for blogging. So it should be as easy as possible for blogposts.

**Comment by developergithubnoreply** [comment]
Got it! :)

**Comment by LouisBarranqueiro** [comment]
Got it! :)

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak 1.2.0](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.2.0) is here and fix this bug :)
