### ISSUE TITLE
wrong pagination in your demo site

### ISSUE THREAD

**Issue by timwangdev** [LouisBarranqueiro/tranquilpeak-hexo-theme#46]
"NEWER POSTS" linked to a wrong url (/) in this page
http://louisbarranqueiro.github.io/tranquilpeak-hexo-theme/page/2/

I didn't find bugs in /layout/_partial/pagination.ejs . So I suppose that's a config problem?

**Comment by LouisBarranqueiro** [comment]
Yes, I saw that. In local, it work perfectly so i will re-deploy to check if it fix this bug. Thanks you for your feedback :)

**Comment by LouisBarranqueiro** [comment]
This is a real bug ! :) the problem is : if the newer posts is the first page, Hexo generate a link without the `config.root` (eg : `/` instead of `/root/`. On local, it's work fine because Hexo redirect `/` to `/root/` but on GitHub that is not the case. To overcome this, I will temporary add a condition to generate manually the URL, and report this bug on Hexo repository. Thanks you for feedback man :)

**Comment by LouisBarranqueiro** [comment]
I fixed temporarily this bug. It will be release on new version (in 2 days I think) :)
