### ISSUE TITLE
Category still exists after deleting all the posts of that category

### ISSUE THREAD

**Issue by eaglesky** [LouisBarranqueiro/tranquilpeak-hexo-theme#53]
Hi Louis, 

I tried your theme and I found that after I deleted all the posts of a certain category( say A), when I clicked on "Categories", A was still there. Wouldn't it be nicer if that category was also removed?

BTW, as you said in the user documentation I downloaded the zip file, but I found that the problem mentioned [here](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/issues/45) had not been fixed in that code. I just wonder if the code in the development branch is actually the latest version.

Thank you for sharing your theme.

Best,

Yalun

**Comment by LouisBarranqueiro** [comment]
Hi man, this issue is not linked to the theme. You have to run `hexo clean` and regenerate the blog with `hexo generate`then all tags and categories not used will be deleted. please download the master branch, it's the latest version, the `dev` branch represent the version in development so potentially not stable. To day, I will release the new version 1.20, be patient :)

**Comment by eaglesky** [comment]
Thank you so much. You're right. That problem has nothing to do with your theme. 

I'm looking forward to your new version. I would say your theme is one of the best blog theme I've ever seen so far. I especially like the category hierarchy which a lot of other themes don't have.  Thank you very much for your efforts!

**Comment by LouisBarranqueiro** [comment]
Yes, in some hours it will be available. Thank you guy, i really appreciate :)
