### ISSUE TITLE
Github Page build failed: Missing submodule

### ISSUE THREAD

**Issue by Sophiai** [LouisBarranqueiro/tranquilpeak-hexo-theme#61]
Hi Louis,I got a problem again. T_T
When I deploy the blog to the GitHub, Github warning:

> Your site is having problems building: The submodule themes/tranquilpeak was not properly initialized with a .gitmodules file. For more information, see https://help.github.com/articles/page-build-failed-missing-submodule.

I try run git submodule init,but it fail
![image](https://cloud.githubusercontent.com/assets/8564932/8839866/a8df4f9a-310c-11e5-9709-1d1de5eda284.png)
 then git submodule update
![image](https://cloud.githubusercontent.com/assets/8564932/8839878/c0877e38-310c-11e5-9d32-cd886373d1a5.png)
run Jekyll locally,all going well;
my blog site is https://github.com/Sophiai/sophiai.github.io

**Comment by h404bi** [comment]
This is no the theme's problem, you should search how to use `git submodule`, or just put the theme's files (simply use [built version](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases)) into the themes folder instead of using git submodule.

**Comment by LouisBarranqueiro** [comment]
@h404bi is right. You have to learn how to use submodule and subtree. Please check the official git tutorial (or others : [here](https://medium.com/@v/git-subtrees-a-tutorial-6ff568381844) or [here](https://git-scm.com/book/en/v2/Git-Tools-Submodules)) and choose which one is the best to do what you want. But this issue is not linked to the theme.
