### ISSUE TITLE
Chinese i18n

### ISSUE THREAD

**Issue by Imyssed** [LouisBarranqueiro/tranquilpeak-hexo-theme#97]
Firstly thanks for this wonderful theme!
It seems that this theme has many Chinese users,so I made some changes to the theme.I put them in [This Repo](https://github.com/Imyssed/Tranquilpeak-Akari.ver) because the changes are just for Chinese users.And because of this,I'm not looking forward to merge these changes.

Also want to add my blog to Showcase:
* URL : http://imyssed.com
* Changes : 
 * Fully Chinese i18n(comments,search,share,etc.)
 * Style,Font

BTW,there's a bug in the `post-action` bar.For example,[this article](http://imyssed.com/Hexo-Docs-1/) has a toc,and the button on the left should link to `#table-of-contents`,but in fact it link to `#` just like it doesn't have a toc.
Sorry for my poor coding skill,I can't find what's wrong in the source code.Hope solving soon.

**Comment by h404bi** [comment]
For showcase, you can open a new pull request. And I recommend a new branch (e.g. branch `showcase`) should be created to receive all those showcase pull requests, instead of merging them into the source code branch (`master` / `dev`).

For that bug, yes, I think it's a bug, the same issue can be found on the official [demo page](https://louisbarranqueiro.github.io/tranquilpeak-hexo-theme/2015/06/15/Welcome-to-the-new-Tranquilpeak/). But I don't know why. [layout/_partial/post/actions.ejs#L55](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/layout/_partial/post/actions.ejs#L55)

cc @LouisBarranqueiro

**Comment by LouisBarranqueiro** [comment]
Thanks you @Imyssed. It's a bug, could you open an issue for this. I have already fix this one but I want to link the commit with the issue (bug) please. :)

About your theme, I don't know if the showcase is the right place for your work. I think, i'm gonna create a wiki to present customized version (css and js mainly) and also special version of Tranquilpeak like yours. :)

**Comment by LouisBarranqueiro** [comment]
@Imyssed  Please respect terms of the GNU General Public License v3.0 :)

**Comment by Imyssed** [comment]
Oh,I've forgotten it:joy:I'll add it soon.
BTW,there's a bug in archives page.The disply of date format and placeholder in the search form don't follow the language settings.
I'm not convenient to pull request,but I fixed it here.
https://github.com/Imyssed/tranquilpeak-hexo-theme/commit/6f78d46de9f53580ad525917a3fc4079312a8182

**Comment by LouisBarranqueiro** [comment]
Yeah, you are right! i will fix that. Thank you :) 

To do it simple, keep package.json file which contains authors and licence :)

**Comment by LouisBarranqueiro** [comment]
Open an issue about bug of table of content button please :)

**Comment by h404bi** [comment]
@LouisBarranqueiro or your can open by yourself. :sweat:

**Comment by LouisBarranqueiro** [comment]
Oh, it discover the bug, so he can create the issue :D

**Comment by LouisBarranqueiro** [comment]
But neverminds, i reference this issue on the commit :D.
